apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-secrets
spec:
  refreshInterval: {{ .Values.aws.secretManager.refreshInterval }}
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.aws.secretManager.targetKubeSecret }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ tpl .Values.aws.secretManager.secretName . | quote }}
    - extract:
        key: {{ tpl .Values.aws.secretManager.secretNameManual . | quote }}