apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "external-secrets-{{name}}"
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
    spec:
      project: default
      source:
        chart: external-secrets
        repoURL: https://charts.external-secrets.io
        targetRevision: 2.5.0
        helm:
          releaseName: external-secrets
      destination:
        namespace: external-secrets
        server: "{{server}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-sa
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "external-secrets-sa-{{name}}"
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
    spec:
      project: default
      source:
        repoURL: https://github.com/GrubzoFood/grubzo-k8s.git
        targetRevision: release/1.0
        path: argocd/common/manifests
        directory:
          include: "external-secrets.serviceaccount.yaml"
      destination:
        namespace: kube-system
        server: "{{server}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
